//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoNature.Visualisation.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertiesEditorGridAndFlyOut_Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesEditorGridAndFlyOut_Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoNature.Visualisation.Desktop.PropertiesEditorGridAndFlyOut.Translation", typeof(PropertiesEditorGridAndFlyOut_Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties editing.
        /// </summary>
        internal static string PropertiesEditFlyOutHeader {
            get {
                return ResourceManager.GetString("PropertiesEditFlyOutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel=&quot;Zrušit&quot;
        ///OK=&quot;OK&quot;
        ///PropertiesEditFlyOutHeader=&quot;Editace vlastností
        ///propertyColumnHeader=&quot;Vlastnost&quot;
        ///valueColumnHeader=&quot;Hodnota&quot;.
        /// </summary>
        internal static string PropertiesEditorGridAndFlyOut_Translation_cs_CZ {
            get {
                return ResourceManager.GetString("PropertiesEditorGridAndFlyOut_Translation_cs_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel=&quot;Cancel&quot;
        ///OK=&quot;OK&quot;
        ///PropertiesEditFlyOutHeader=&quot;Properties editing&quot;
        ///propertyColumnHeader=&quot;Property&quot;
        ///valueColumnHeader=&quot;Value&quot;.
        /// </summary>
        internal static string PropertiesEditorGridAndFlyOut_Translation_en_US {
            get {
                return ResourceManager.GetString("PropertiesEditorGridAndFlyOut_Translation_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string propertyColumnHeader {
            get {
                return ResourceManager.GetString("propertyColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string valueColumnHeaderValue {
            get {
                return ResourceManager.GetString("valueColumnHeaderValue", resourceCulture);
            }
        }
    }
}
